### PR TITLE
Support for head mods

### PR DESCRIPTION
**Pull request by MediaMoots**
This PR makes the Exporter properly export head mods, but the Blender plugin still needs to be updated to support different material names and shapekeys.

One possibility may be to use the SMR Data:
image

and check the corresponding material name:
image

Also, all body meshes are all set to `"CoordinateType":-1` in the Json file.

### CODE REVIEW

**Comment by MediaMoots** [comment]
V3.98
Export separate eyes when using head mod
Export eyes for each outfit for some cards that have different eye overlays for each outfit.

image
Format is `MatName_Type_OutfitNumber`

**Comment by poisenbery** [comment]
[importing.zip](https://github.com/FlailingFog/KK-Blender-Porter-Pack/files/9905559/importing.zip)
Dummy fix of "importeverything.py" and "separatebody.py"

Renames the materials and adds the textures, minus the additional eyes.
This at least allows the models to be imported into blender for the time being.

**Comment by MediaMoots** [comment]
@poisenbery 
Thanks! Thats looks great.

I wonder if there's a way to do it without hardcoding all values... since other head mods may have different names.

Probably with the json files...

**Comment by poisenbery** [comment]
> without hardcoding all values

That's why I called it a "dummy fix"
 I'm not smart enough to figure out how to do it properly.

**Pull request merged**
